// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8OPZd82IznrKQt2uwz2U95GGWqqa7Md4',
    appId: '1:251404394716:web:f2969295ad7ea1949dd419',
    messagingSenderId: '251404394716',
    projectId: 'lab13-85899',
    authDomain: 'lab13-85899.firebaseapp.com',
    storageBucket: 'lab13-85899.firebasestorage.app',
    measurementId: 'G-ESRN66TKZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA02vklbvOL24KlaRJDGB-68i4d8StKQx8',
    appId: '1:251404394716:android:ac3c6892fbdf6bf29dd419',
    messagingSenderId: '251404394716',
    projectId: 'lab13-85899',
    storageBucket: 'lab13-85899.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8OPZd82IznrKQt2uwz2U95GGWqqa7Md4',
    appId: '1:251404394716:web:ff409e4ef3b9287f9dd419',
    messagingSenderId: '251404394716',
    projectId: 'lab13-85899',
    authDomain: 'lab13-85899.firebaseapp.com',
    storageBucket: 'lab13-85899.firebasestorage.app',
    measurementId: 'G-W17HEDF5R8',
  );
}
